//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class AppIcons {
  static const String _family = 'iconfont';
  
  AppIcons._();
  
  static const IconData shujujicheng = IconData(0xe862, fontFamily: _family); // 数据集成
  static const IconData si_glyph_bubble_chat = IconData(0xe615, fontFamily: _family); // si-glyph-bubble-chat
  static const IconData kanban_1 = IconData(0xe742, fontFamily: _family); // kanban
  static const IconData search = IconData(0xe652, fontFamily: _family); // search
  static const IconData jinrudaobo = IconData(0xe616, fontFamily: _family); // 进入导播
  static const IconData icon_meeting = IconData(0xe637, fontFamily: _family); // icon_meeting
  static const IconData meetvideo_endmeet = IconData(0xe63a, fontFamily: _family); // Meetvideo_endmeet
  static const IconData fangda = IconData(0xe614, fontFamily: _family); // 放大
  static const IconData suoxiao = IconData(0xe613, fontFamily: _family); // 缩小
  static const IconData share = IconData(0xe60e, fontFamily: _family); // 分享/share
  static const IconData zichan = IconData(0xe611, fontFamily: _family); // 资产
  static const IconData xiangmu = IconData(0xe62e, fontFamily: _family); // 项目
  static const IconData zuidahua = IconData(0xe621, fontFamily: _family); // 最大化
  static const IconData tuopanhua = IconData(0xe60f, fontFamily: _family); // 托盘化
  static const IconData zuixiaohua = IconData(0xe610, fontFamily: _family); // 最小化
  static const IconData chuangkouhua = IconData(0xe612, fontFamily: _family); // 窗口化
  static const IconData tag = IconData(0xe7ae, fontFamily: _family); // tag
  static const IconData youxianji = IconData(0xe679, fontFamily: _family); // 优先级
  static const IconData view = IconData(0xe635, fontFamily: _family); // view
  static const IconData preview = IconData(0xe632, fontFamily: _family); // preview
  static const IconData icon_jinhangzhong = IconData(0xe675, fontFamily: _family); // icon-进行中
  static const IconData todo = IconData(0xea34, fontFamily: _family); // TODO
  static const IconData done = IconData(0xe617, fontFamily: _family); // Done
  static const IconData a_samlogo_fcm = IconData(0xe619, fontFamily: _family); // Sam logo FCM
  static const IconData yuanquan = IconData(0xe63e, fontFamily: _family); // 圆圈
  static const IconData chart_18 = IconData(0xe677, fontFamily: _family); // 进度1
  static const IconData chart_34 = IconData(0xe678, fontFamily: _family); // 进度6
  static const IconData ziyuan = IconData(0xe648, fontFamily: _family); // 曲别针
  static const IconData organcode = IconData(0xe60c, fontFamily: _family); // organcode
  static const IconData zuzhi_data_organization_6 = IconData(0xe671, fontFamily: _family); // 组织Data Organization (6)
  static const IconData zuzhi_data_organization_7 = IconData(0xe672, fontFamily: _family); // 组织Data Organization (7)
  static const IconData organization = IconData(0xe97b, fontFamily: _family); // organization
  static const IconData wangye = IconData(0xe706, fontFamily: _family); // 网页
  static const IconData shebei = IconData(0xe720, fontFamily: _family); // 设备
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class AppIconsPreview extends StatelessWidget {
  const AppIconsPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(AppIcons.shujujicheng, "shujujicheng", "数据集成"),
    _PreviewIcon(AppIcons.si_glyph_bubble_chat, "si_glyph_bubble_chat", "si-glyph-bubble-chat"),
    _PreviewIcon(AppIcons.kanban_1, "kanban_1", "kanban"),
    _PreviewIcon(AppIcons.search, "search", "search"),
    _PreviewIcon(AppIcons.jinrudaobo, "jinrudaobo", "进入导播"),
    _PreviewIcon(AppIcons.icon_meeting, "icon_meeting", "icon_meeting"),
    _PreviewIcon(AppIcons.meetvideo_endmeet, "meetvideo_endmeet", "Meetvideo_endmeet"),
    _PreviewIcon(AppIcons.fangda, "fangda", "放大"),
    _PreviewIcon(AppIcons.suoxiao, "suoxiao", "缩小"),
    _PreviewIcon(AppIcons.share, "share", "分享/share"),
    _PreviewIcon(AppIcons.zichan, "zichan", "资产"),
    _PreviewIcon(AppIcons.xiangmu, "xiangmu", "项目"),
    _PreviewIcon(AppIcons.zuidahua, "zuidahua", "最大化"),
    _PreviewIcon(AppIcons.tuopanhua, "tuopanhua", "托盘化"),
    _PreviewIcon(AppIcons.zuixiaohua, "zuixiaohua", "最小化"),
    _PreviewIcon(AppIcons.chuangkouhua, "chuangkouhua", "窗口化"),
    _PreviewIcon(AppIcons.tag, "tag", "tag"),
    _PreviewIcon(AppIcons.youxianji, "youxianji", "优先级"),
    _PreviewIcon(AppIcons.view, "view", "view"),
    _PreviewIcon(AppIcons.preview, "preview", "preview"),
    _PreviewIcon(AppIcons.icon_jinhangzhong, "icon_jinhangzhong", "icon-进行中"),
    _PreviewIcon(AppIcons.todo, "todo", "TODO"),
    _PreviewIcon(AppIcons.done, "done", "Done"),
    _PreviewIcon(AppIcons.a_samlogo_fcm, "a_samlogo_fcm", "Sam logo FCM"),
    _PreviewIcon(AppIcons.yuanquan, "yuanquan", "圆圈"),
    _PreviewIcon(AppIcons.chart_18, "chart_18", "进度1"),
    _PreviewIcon(AppIcons.chart_34, "chart_34", "进度6"),
    _PreviewIcon(AppIcons.ziyuan, "ziyuan", "曲别针"),
    _PreviewIcon(AppIcons.organcode, "organcode", "organcode"),
    _PreviewIcon(AppIcons.zuzhi_data_organization_6, "zuzhi_data_organization_6", "组织Data Organization (6)"),
    _PreviewIcon(AppIcons.zuzhi_data_organization_7, "zuzhi_data_organization_7", "组织Data Organization (7)"),
    _PreviewIcon(AppIcons.organization, "organization", "organization"),
    _PreviewIcon(AppIcons.wangye, "wangye", "网页"),
    _PreviewIcon(AppIcons.shebei, "shebei", "设备"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('AppIcons'),
      ),
      body: SingleChildScrollView(
        child: GridView.count(
          shrinkWrap: true,
          crossAxisCount: 4,
          children: iconList.map((e) {
            return InkWell(
              onTap: () {
                //
              },
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    margin: const EdgeInsets.only(bottom: 8),
                    child: Icon(e.icon),
                  ),
                  Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                  Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                ],
              ),
            );
          }).toList(),
        ),
      ),
    );
  }
}
